server:
  port: 8081

# Configure Keycloak Adapter
keycloak:
  realm: poc
  resource: backend-service
  auth-server-url: http://localhost:8080/
  ssl-required: external
  credentials:
    secret: Bl5UJPsnmZrx6neFECWVVGpC9RvBrQoz
  security-constraints:
  - auth-roles:
    - "*"
    security-collections:
    - patterns:
      - "/api/*"
  policy-enforcer-config:
    enforcement-mode: enforcing
    http-method-as-scope: true
           
# Turn off the logs
logging:
  level:
    root: info
